general {
    # Disabling full keyboard grab so you can check values via hyprctl in another split
    grab_focus = false
}

finders {
    default_finder = desktop
    math_prefix = =
    unicode_prefix = .
    desktop_icons = true
}

ui {
    border_radius = 12
    border_size = 8
    window_size = 600 300
    
    font_family = "JetBrainsMono Nerd Font"
    font_size = 13

    colors {
        # Using a transparent alpha channel (0x66) so the compositor blur can actually work!
        background = 0x66000000        
        border = 0xff38bdf8            
        text = 0xffbae6fd              
        highlight = 0xff059669         
    }
}
